### ISSUE TITLE
Plagiarism 

### ISSUE THREAD

**Issue by RDIL** [ChromizedClient/Client#1]
You basically took the Hyperium README and put it here xD 
Debating if I should DMCA this organization. 
@simonri @Chromized

**Comment by RDIL** [comment]
Wondering if Mitch, FalseHonesy, kerbybit, Google, Semx11, 2Pi, etc. have given you permission to copy all your code. 

I know you didn’t ask me if you could take my code...

**Comment by simonri** [comment]
Please contact me on Discord:
SimonRi#6295
Let's sort this misinterpretation out.
